# Generated by Django 3.1.6 on 2021-03-03 14:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.unique_code_genarator, max_length=8, null=True, unique=True),
        ),
    ]
