# Generated by Django 3.1.7 on 2021-03-03 15:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210303_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.unique_code_genarator, max_length=8, unique=True),
        ),
    ]
